/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion.GuiCliente;

import Aplicacion.Service.AnimalService;
import Aplicacion.Service.RazaService;
import Dominio.Modelo.Animal;
import Dominio.Modelo.Raza;

import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author neker
 */
public class PanelCatalogo extends javax.swing.JPanel {

    private final AnimalService animalService = new AnimalService();
    private final RazaService razaService = new RazaService();
    private final Map<Integer, String> razasMap = new HashMap<>();

    /**
     * Creates new form PanelCatalogo
     */
    public PanelCatalogo() {
        initComponents();
        initLogic();
    }

    private void initLogic() {
        DefaultTableModel modelo = new DefaultTableModel(
                new Object[]{"ID", "Nombre", "Raza", "Sexo", "Edad", "Precio", "Stock", "Estado"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblCatalogo.setModel(modelo);
        cargarRazas();
        cargarAnimales();
    }

    private void cargarRazas() {
        razasMap.clear();
        for (Raza raza : razaService.findAll()) {
            razasMap.put(raza.getIdRaza(), raza.getNombre());
        }
    }

    private void cargarAnimales() {
        DefaultTableModel modelo = (DefaultTableModel) tblCatalogo.getModel();
        modelo.setRowCount(0);
        try {
            for (Animal animal : animalService.findAll()) {
                String nombreRaza = razasMap.getOrDefault(animal.getIdRaza(), "N/A");
                modelo.addRow(new Object[]{
                        animal.getIdAnimal(),
                        animal.getNombre(),
                        nombreRaza,
                        animal.getSexo(),
                        animal.getEdad(),
                        String.format("S/ %.2f", animal.getPrecio()),
                        animal.getStock(),
                        animal.getEstado()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar animales: " + e.getMessage());
        }
    }

    public void recargar() {
        cargarRazas();
        cargarAnimales();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCatalogoTop = new javax.swing.JPanel();
        txtTituloAnimales = new javax.swing.JLabel();
        btnAgregarCarrito = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCatalogo = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanelCatalogoTop.setPreferredSize(new java.awt.Dimension(400, 50));

        txtTituloAnimales.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        txtTituloAnimales.setText("Animales disponibles");

        btnAgregarCarrito.setText("Agregar al Carrito");
        btnAgregarCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCarritoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCatalogoTopLayout = new javax.swing.GroupLayout(jPanelCatalogoTop);
        jPanelCatalogoTop.setLayout(jPanelCatalogoTopLayout);
        jPanelCatalogoTopLayout.setHorizontalGroup(
            jPanelCatalogoTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCatalogoTopLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(txtTituloAnimales, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 401, Short.MAX_VALUE)
                .addComponent(btnAgregarCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanelCatalogoTopLayout.setVerticalGroup(
            jPanelCatalogoTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCatalogoTopLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanelCatalogoTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTituloAnimales)
                    .addComponent(btnAgregarCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        add(jPanelCatalogoTop, java.awt.BorderLayout.PAGE_START);

        tblCatalogo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Raza", "Sexo", "Edad", "Precio", "Stock", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tblCatalogo);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCarritoActionPerformed
        int fila = tblCatalogo.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Selecciona un animal de la tabla.");
            return;
        }
        int modeloFila = tblCatalogo.convertRowIndexToModel(fila);
        DefaultTableModel modelo = (DefaultTableModel) tblCatalogo.getModel();
        int idAnimal = (int) modelo.getValueAt(modeloFila, 0);

        Animal animal = animalService.findById(idAnimal).orElse(null);
        if (animal == null) {
            JOptionPane.showMessageDialog(this, "No se encontro el animal.");
            return;
        }
        if ("Vendido".equals(animal.getEstado())) {
            JOptionPane.showMessageDialog(this, "Este animal ya fue vendido.");
            return;
        }

        java.awt.Component parent = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (parent instanceof FrmCliente) {
            ((FrmCliente) parent).agregarAlCarrito(animal);
        }
    }//GEN-LAST:event_btnAgregarCarritoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCarrito;
    private javax.swing.JPanel jPanelCatalogoTop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCatalogo;
    private javax.swing.JLabel txtTituloAnimales;
    // End of variables declaration//GEN-END:variables
}
