/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package RunMain;

import Aplicacion.Service.UsuarioServiceImpl;
import Dominio.Modelo.Usuario;
import Presentacion.GuiAdmin.FrmAdmind;
import Presentacion.GuiUsuario.FrmUsuario;

import java.awt.GridBagLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author yordan aquiles andres quiroz
 */
public class LoginF extends javax.swing.JPanel {

    public LoginF() {
        initComponents();
        configurarFondoResponsivo();
    }

    private void configurarFondoResponsivo() {
        this.setLayout(new GridBagLayout());
        this.remove(contenedorLogin);
        contenedorLogin.setMinimumSize(new java.awt.Dimension(1410, 770));
        contenedorLogin.setPreferredSize(new java.awt.Dimension(1410, 770));
        contenedorLogin.setMaximumSize(new java.awt.Dimension(1410, 770));
        this.add(contenedorLogin, new java.awt.GridBagConstraints());
        this.setBackground(new java.awt.Color(240, 238, 233));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorLogin = new javax.swing.JLayeredPane();
        txtUsuario = new javax.swing.JTextField();
        txtPasword = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnIniciarSesion = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(1, 0));

        contenedorLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsuario.setBackground(new java.awt.Color(253, 242, 248));
        txtUsuario.setBorder(null);
        txtUsuario.addActionListener(this::txtUsuarioActionPerformed);
        contenedorLogin.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 370, 250, 30));

        txtPasword.setBackground(new java.awt.Color(253, 243, 250));
        txtPasword.setBorder(null);
        contenedorLogin.add(txtPasword, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 430, 280, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/login.png"))); // NOI18N
        contenedorLogin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1410, 780));

        btnIniciarSesion.setText("jButton1");
        btnIniciarSesion.addActionListener(this::btnIniciarSesionActionPerformed);
        contenedorLogin.add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 533, 360, 30));

        add(contenedorLogin);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        btnIniciarSesion.doClick();
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        String correo = txtUsuario.getText().trim();
        String password = txtPasword.getText().trim();

        if (correo.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese usuario y contraseña.");
            return;
        }

        try {
            UsuarioServiceImpl usuarioService = new UsuarioServiceImpl();
            Usuario usuario = usuarioService.login(correo, password);

            if (usuario == null) {
                JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos.");
                return;
            }

            if (usuario.getIdRol() == 1) {
                FrmAdmind guiAdmin = new FrmAdmind();
                guiAdmin.setVisible(true);
            } else if (usuario.getIdRol() == 2) {
                FrmUsuario guiUsuario = new FrmUsuario();
                guiUsuario.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Rol no reconocido.");
            }
        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(this, "No se pudo validar el usuario con la base de datos.");
        }
    }//GEN-LAST:event_btnIniciarSesionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JLayeredPane contenedorLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtPasword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
