/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package RunMain;

/**
 *
 * @author yordan
 */
public class Main extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Main.class.getName());

    /**
     * Creates new form Main
     */
public Main() {
    initComponents();
    
    // 1. Pantalla completa automática
    this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    
    // 2. Limpieza estándar para asegurar expansión total del contenedor
    contenedorLogin.removeAll();
    contenedorLogin.setLayout(new java.awt.BorderLayout());
    
    // 3. Agregamos tu LoginF corregido
    LoginF login = new LoginF();
    contenedorLogin.add(login, java.awt.BorderLayout.CENTER);
    
    contenedorLogin.revalidate();
    contenedorLogin.repaint();
}

// 🛠️ Creamos tu método void debajo de initComponents()
private void configurarResponsivo() {
    // 1. Forzar pantalla completa automática
    this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    
    // 2. 🌟 EL CAMBIO CLAVE: Obligamos al contenido de la ventana principal a usar BorderLayout
    this.getContentPane().setLayout(new java.awt.BorderLayout());
    
    // 3. Limpiamos por completo el panel contenedor para borrar configuraciones rígidas previas
    contenedorLogin.removeAll();
    contenedorLogin.setLayout(new java.awt.BorderLayout());
    
    // 4. Instanciamos tu LoginF y le exigimos ocupar el CENTER absoluto
    LoginF login = new LoginF();
    contenedorLogin.add(login, java.awt.BorderLayout.CENTER);
    
    // 5. Añadimos el contenedor directamente al centro del JFrame principal
    this.getContentPane().add(contenedorLogin, java.awt.BorderLayout.CENTER);
    
    // 6. Forzar el recálculo matemático de layouts y repintado de píxeles
    this.revalidate();
    this.repaint();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorLogin = new javax.swing.JPanel();
        loginF1 = new RunMain.LoginF();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contenedorLogin.setLayout(new java.awt.BorderLayout());
        contenedorLogin.add(loginF1, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Main().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenedorLogin;
    private RunMain.LoginF loginF1;
    // End of variables declaration//GEN-END:variables
}
