/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion.GuiAdmin;

import java.awt.PopupMenu;

/**
 *
 * @author yordan
 */
public class FrmAdmind extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmAdmind.class.getName());

    /**
     * Creates new form FrmAdmind
     */
    public FrmAdmind() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorPantallas = new javax.swing.JPanel();
        almacen1 = new Presentacion.GuiAdmin.Almacen();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnAlmacen = new javax.swing.JMenu();
        mnVentas = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contenedorPantallas.setLayout(new java.awt.BorderLayout());
        contenedorPantallas.add(almacen1, java.awt.BorderLayout.CENTER);

        mnAlmacen.setText("Almacen");
        mnAlmacen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnAlmacenMouseClicked(evt);
            }
        });
        mnAlmacen.addActionListener(this::mnAlmacenActionPerformed);
        jMenuBar1.add(mnAlmacen);

        mnVentas.setText("Ventas");
        mnVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnVentasMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnVentas);

        jMenu3.setText("Clientes");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("jMenu4");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("jMenu5");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorPantallas, javax.swing.GroupLayout.DEFAULT_SIZE, 1322, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorPantallas, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAlmacenActionPerformed
        contenedorPantallas.removeAll();
        Almacen pantallaAlmacen = new Almacen();
        contenedorPantallas.add(pantallaAlmacen);
    }//GEN-LAST:event_mnAlmacenActionPerformed

    private void mnVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnVentasMouseClicked
           // 1. Limpiamos lo que haya en el contenedor
        contenedorPantallas.removeAll();

        System.out.println("SE PRESIONO EL MENU ALMACEN");

        // 2. Creamos y agregamos la nueva pantalla
        Ventas pantallaVentas = new Ventas();
        contenedorPantallas.add(pantallaVentas);

        // 3. ¡LAS LÍNEAS CLAVE!
        contenedorPantallas.revalidate(); // Re-calcula el diseño (Layout)
        contenedorPantallas.repaint();  
    }//GEN-LAST:event_mnVentasMouseClicked

    private void mnAlmacenMouseClicked(java.awt.event.MouseEvent evt) {                                       
        // 1. Limpiamos lo que haya en el contenedor
        contenedorPantallas.removeAll();

        System.out.println("SE PRESIONO EL MENU ALMACEN");

        // 2. Creamos y agregamos la nueva pantalla
        Almacen pantallaAlmacen = new Almacen();
        contenedorPantallas.add(pantallaAlmacen);

        // 3. ¡LAS LÍNEAS CLAVE!
        contenedorPantallas.revalidate(); // Re-calcula el diseño (Layout)
        contenedorPantallas.repaint();    // Vuelve a pintar visualmente los componentes
    }                                                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmAdmind().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Presentacion.GuiAdmin.Almacen almacen1;
    private javax.swing.JPanel contenedorPantallas;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnAlmacen;
    private javax.swing.JMenu mnVentas;
    // End of variables declaration//GEN-END:variables
}
