/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion.GuiAdmin;

import Dominio.Modelo.Usuario;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author neker
 */
public class FrmAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmAdmin.class.getName());
    private final CardLayout cardLayout = new CardLayout();
    private Usuario usuarioLogueado;
    private PanelDashboard panelDashboard;
    private PanelAnimales panelAnimales;
    private PanelVentas panelVentas;
    private PanelClientes panelClientes;
    private PanelUsuarios panelUsuarios;

    /**
     * Creates new form FrmAdmin
     */
    public FrmAdmin() {
        this(null);
    }

    public FrmAdmin(Usuario usuarioLogueado) {
        this.usuarioLogueado = usuarioLogueado;
        initComponents();
        configurarVista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAnimalesStock = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        btnDashboard = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanelHeader = new javax.swing.JPanel();
        txtTituloPanel = new javax.swing.JLabel();
        txtUserName = new javax.swing.JLabel();
        jPanelBoddy = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(31, 45, 42));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(180, 700));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GRANJA ADMIN");

        btnAnimalesStock.setBackground(new java.awt.Color(0, 132, 78));
        btnAnimalesStock.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAnimalesStock.setForeground(new java.awt.Color(255, 255, 255));
        btnAnimalesStock.setText("Animales/Stock");
        btnAnimalesStock.setMaximumSize(new java.awt.Dimension(150, 45));
        btnAnimalesStock.setPreferredSize(new java.awt.Dimension(150, 50));

        btnVentas.setBackground(new java.awt.Color(0, 132, 78));
        btnVentas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVentas.setForeground(new java.awt.Color(255, 255, 255));
        btnVentas.setText("Ventas");
        btnVentas.setMaximumSize(new java.awt.Dimension(150, 45));
        btnVentas.setPreferredSize(new java.awt.Dimension(150, 50));

        btnClientes.setBackground(new java.awt.Color(0, 132, 78));
        btnClientes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClientes.setForeground(new java.awt.Color(255, 255, 255));
        btnClientes.setText("Clientes");
        btnClientes.setMaximumSize(new java.awt.Dimension(150, 45));
        btnClientes.setPreferredSize(new java.awt.Dimension(150, 50));

        btnUsuarios.setBackground(new java.awt.Color(0, 132, 78));
        btnUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setText("Usuarios");
        btnUsuarios.setMaximumSize(new java.awt.Dimension(150, 45));
        btnUsuarios.setPreferredSize(new java.awt.Dimension(150, 50));

        btnCerrarSesion.setBackground(new java.awt.Color(0, 132, 78));
        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setText("Cerrar sesion");
        btnCerrarSesion.setMaximumSize(new java.awt.Dimension(150, 45));
        btnCerrarSesion.setPreferredSize(new java.awt.Dimension(150, 50));

        btnDashboard.setBackground(new java.awt.Color(0, 132, 78));
        btnDashboard.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDashboard.setForeground(new java.awt.Color(255, 255, 255));
        btnDashboard.setText("Dashboard");
        btnDashboard.setMaximumSize(new java.awt.Dimension(150, 45));
        btnDashboard.setPreferredSize(new java.awt.Dimension(150, 50));
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAnimalesStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAnimalesStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanelHeader.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtTituloPanel.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        txtTituloPanel.setForeground(new java.awt.Color(25, 40, 37));
        txtTituloPanel.setText("TituloPanel");

        txtUserName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUserName.setForeground(new java.awt.Color(150, 160, 156));
        txtUserName.setText("User: User");

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(txtTituloPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 546, Short.MAX_VALUE)
                .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUserName)
                    .addComponent(txtTituloPanel))
                .addGap(24, 24, 24))
        );

        jPanelBoddy.setForeground(new java.awt.Color(255, 255, 255));
        jPanelBoddy.setPreferredSize(new java.awt.Dimension(920, 630));

        javax.swing.GroupLayout jPanelBoddyLayout = new javax.swing.GroupLayout(jPanelBoddy);
        jPanelBoddy.setLayout(jPanelBoddyLayout);
        jPanelBoddyLayout.setHorizontalGroup(
            jPanelBoddyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelBoddyLayout.setVerticalGroup(
            jPanelBoddyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelBoddy, javax.swing.GroupLayout.DEFAULT_SIZE, 924, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBoddy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configurarVista() {
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);

        jPanel2.setBackground(new Color(244, 247, 246));
        jPanelHeader.setBackground(Color.WHITE);
        jPanelBoddy.setLayout(cardLayout);
        jPanelBoddy.setBackground(new Color(244, 247, 246));

        panelDashboard = new PanelDashboard();
        panelAnimales = new PanelAnimales();
        panelVentas = new PanelVentas();
        panelClientes = new PanelClientes();
        panelUsuarios = new PanelUsuarios();

        jPanelBoddy.add(panelDashboard, "dashboard");
        jPanelBoddy.add(panelAnimales, "animales");
        jPanelBoddy.add(panelVentas, "ventas");
        jPanelBoddy.add(panelClientes, "clientes");
        jPanelBoddy.add(panelUsuarios, "usuarios");

        String nombre = usuarioLogueado != null ? usuarioLogueado.getNombre() : "Admin";
        txtUserName.setText("Admin: " + nombre);

        mostrarPanel("dashboard", "Dashboard");

        btnAnimalesStock.addActionListener(e -> mostrarPanel("animales", "Animales / Stock"));
        btnVentas.addActionListener(e -> mostrarPanel("ventas", "Ventas"));
        btnClientes.addActionListener(e -> mostrarPanel("clientes", "Clientes"));
        btnUsuarios.addActionListener(e -> mostrarPanel("usuarios", "Usuarios"));
        btnCerrarSesion.addActionListener(e -> cerrarSesion());
    }

    private void mostrarPanel(String nombrePanel, String titulo) {
        txtTituloPanel.setText(titulo);
        cardLayout.show(jPanelBoddy, nombrePanel);

        switch (nombrePanel) {
            case "dashboard" -> {
                if (panelDashboard != null) panelDashboard.cargarDatos();
            }
            case "animales" -> {
                if (panelAnimales != null) panelAnimales.cargarDatos();
            }
            case "ventas" -> {
                if (panelVentas != null) panelVentas.cargarDatos();
            }
            case "clientes" -> {
                if (panelClientes != null) panelClientes.cargarDatos();
            }
            case "usuarios" -> {
                if (panelUsuarios != null) panelUsuarios.cargarDatos();
            }
            default -> {
            }
        }
    }

    private void cerrarSesion() {
        int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Desea cerrar sesión?",
                "Cerrar sesión",
                JOptionPane.YES_NO_OPTION
        );

        if (opcion == JOptionPane.YES_OPTION) {
            new RunMain.Main().setVisible(true);
            dispose();
        }
    }

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        mostrarPanel("dashboard", "Dashboard");
    }//GEN-LAST:event_btnDashboardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnimalesStock;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JButton btnVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelBoddy;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JLabel txtTituloPanel;
    private javax.swing.JLabel txtUserName;
    // End of variables declaration//GEN-END:variables
}
