/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion.GuiAdmin;

import Dominio.Modelo.Usuario;
import javax.swing.JPanel;

/**
 *
 * @author yordan
 */
public class HomeAdmin extends javax.swing.JPanel {

    /**
     * Creates new form HomeAdmin
     */
    public HomeAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bntAlmacen = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnConfig = new javax.swing.JButton();
        contenedorNavegacion = new javax.swing.JPanel();
        almacen1 = new Presentacion.GuiAdmin.Almacen();

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        bntAlmacen.setText("Almacen");
        bntAlmacen.addActionListener(this::bntAlmacenActionPerformed);

        btnVentas.setText("Ventas");
        btnVentas.addActionListener(this::btnVentasActionPerformed);

        btnClientes.setText("Clientes");

        btnConfig.setText("Config");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bntAlmacen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
            .addComponent(btnClientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnConfig, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnVentas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(bntAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(btnVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115)
                .addComponent(btnConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );

        contenedorNavegacion.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout contenedorNavegacionLayout = new javax.swing.GroupLayout(contenedorNavegacion);
        contenedorNavegacion.setLayout(contenedorNavegacionLayout);
        contenedorNavegacionLayout.setHorizontalGroup(
            contenedorNavegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(almacen1, javax.swing.GroupLayout.DEFAULT_SIZE, 1287, Short.MAX_VALUE)
        );
        contenedorNavegacionLayout.setVerticalGroup(
            contenedorNavegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(almacen1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenedorNavegacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contenedorNavegacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        // TODO add your handling code here:
        Ventas ventas= new Ventas();
        cambiarPantalla(ventas);
        
    }//GEN-LAST:event_btnVentasActionPerformed

    private void bntAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAlmacenActionPerformed
        // TODO add your handling code here:
        cambiarPantalla(almacen1);
    }//GEN-LAST:event_bntAlmacenActionPerformed
void cambiarPantalla(JPanel nuevaPantalla){
    // 1. Limpiamos el panel actual
    contenedorNavegacion.removeAll();
    
    // 2. Le aseguramos un Layout dinámico (Por si NetBeans le puso GroupLayout)
    contenedorNavegacion.setLayout(new java.awt.BorderLayout());
    
    // 3. Agregamos la nueva pantalla expandida en todo el CENTRO
    contenedorNavegacion.add(nuevaPantalla, java.awt.BorderLayout.CENTER);
    
    // 4. LE AVISAMOS A SWING QUE SE REDIBUJE (Esto evita que quede en blanco)
    contenedorNavegacion.revalidate();
    contenedorNavegacion.repaint();
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Presentacion.GuiAdmin.Almacen almacen1;
    private javax.swing.JButton bntAlmacen;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnConfig;
    private javax.swing.JButton btnVentas;
    private javax.swing.JPanel contenedorNavegacion;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
