/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion.GuiAdmin;

import Aplicacion.Service.UsuarioService;
import Dominio.Modelo.Usuario;

import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import java.util.List;
import java.util.Optional;
import javax.swing.BorderFactory;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author neker
 */
public class PanelUsuarios extends javax.swing.JPanel {

    private final UsuarioService usuarioService = new UsuarioService();
    private final DefaultTableModel modelo = new DefaultTableModel(
            new Object[]{"ID", "Rol", "Nombre", "Correo", "Estado"}, 0
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    /**
     * Creates new form PanelAnimales
     */
    public PanelUsuarios() {
        initComponents();
        setBackground(new Color(244, 247, 246));
        configurarTabla();
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(920, 630));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(25, 40, 37));
        jLabel1.setText("Usuarios del sistema");

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Rol", "Nombre", "Correo", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tblUsuarios);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 886, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditar)
                .addGap(156, 156, 156))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        editarUsuarioSeleccionado();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void configurarTabla() {
        tblUsuarios.setModel(modelo);
        tblUsuarios.setRowHeight(28);
        tblUsuarios.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 13));
        jScrollPane1.setBorder(BorderFactory.createLineBorder(new Color(225, 231, 229)));
    }

    public final void cargarDatos() {
        modelo.setRowCount(0);
        try {
            List<Usuario> usuarios = usuarioService.findAll();
            for (Usuario usuario : usuarios) {
                modelo.addRow(new Object[]{
                        usuario.getIdUsuario(),
                        usuario.getIdRol() == 1 ? "ADMIN" : "CLIENTE",
                        usuario.getNombre(),
                        usuario.getCorreo(),
                        usuario.isEstado() ? "Activo" : "Inactivo"
                });
            }
        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(this, "No se pudieron cargar los usuarios.");
        }
    }

    private void editarUsuarioSeleccionado() {
        int selectedRow = tblUsuarios.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un usuario.");
            return;
        }

        int modelRow = tblUsuarios.convertRowIndexToModel(selectedRow);
        int idUsuario = (int) modelo.getValueAt(modelRow, 0);
        Optional<Usuario> usuarioEncontrado = usuarioService.findById(idUsuario);
        if (usuarioEncontrado.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No se encontro el usuario seleccionado.");
            return;
        }

        Usuario usuario = usuarioEncontrado.get();
        JTextField txtNombre = new JTextField(usuario.getNombre());
        JTextField txtCorreo = new JTextField(usuario.getCorreo());
        JComboBox<String> cmbRol = new JComboBox<>(new String[]{"1 - ADMIN", "2 - CLIENTE"});
        cmbRol.setSelectedIndex(usuario.getIdRol() == 1 ? 0 : 1);
        JCheckBox chkActivo = new JCheckBox("Activo", usuario.isEstado());

        JPanel form = new JPanel(new GridLayout(0, 1, 0, 8));
        form.setBorder(new EmptyBorder(8, 8, 8, 8));
        form.add(new JLabel("Nombre"));
        form.add(txtNombre);
        form.add(new JLabel("Correo"));
        form.add(txtCorreo);
        form.add(new JLabel("Rol"));
        form.add(cmbRol);
        form.add(chkActivo);

        int result = JOptionPane.showConfirmDialog(this, form, "Editar usuario", JOptionPane.OK_CANCEL_OPTION);
        if (result != JOptionPane.OK_OPTION) {
            return;
        }

        usuario.setNombre(txtNombre.getText().trim());
        usuario.setCorreo(txtCorreo.getText().trim());
        usuario.setIdRol(cmbRol.getSelectedIndex() == 0 ? 1 : 2);
        usuario.setEstado(chkActivo.isSelected());

        try {
            int filas = usuarioService.update(usuario);
            if (filas > 0) {
                JOptionPane.showMessageDialog(this, "Usuario actualizado.");
                cargarDatos();
            } else {
                JOptionPane.showMessageDialog(this, "No se actualizo el usuario.");
            }
        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(this, "No se pudo actualizar el usuario.");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsuarios;
    // End of variables declaration//GEN-END:variables
}
