/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion.GuiAdmin;

import Aplicacion.Service.AnimalService;
import Aplicacion.Service.RazaService;
import Dominio.Modelo.Animal;
import Dominio.Modelo.Raza;

import java.awt.Color;
import java.awt.Font;
import java.util.Locale;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author neker
 */
public class PanelAnimales extends javax.swing.JPanel {

    private final AnimalService animalService = new AnimalService();
    private final RazaService razaService = new RazaService();
    private final DefaultTableModel modelo = new DefaultTableModel(
            new Object[]{"ID", "Raza", "Nombre", "Sexo", "Edad", "Precio", "Stock", "Estado"}, 0
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    /**
     * Creates new form PanelAnimales
     */
    public PanelAnimales() {
        initComponents();
        setBackground(new Color(244, 247, 246));
        configurarTabla();
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAnimales = new javax.swing.JTable();
        btnEditarPrecio = new javax.swing.JButton();
        btnEditSctockEstado = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(920, 630));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(25, 40, 37));
        jLabel1.setText("Listado y stock de animales");

        tblAnimales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Raza", "Nombre", "Sexo", "Edad", "Precio", "Stock", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tblAnimales);

        btnEditarPrecio.setText("Editar Precio");
        btnEditarPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPrecioActionPerformed(evt);
            }
        });

        btnEditSctockEstado.setText("Editar Stcok y Estado");
        btnEditSctockEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditSctockEstadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 873, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(17, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditSctockEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditarPrecio)
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarPrecio)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditSctockEstado))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPrecioActionPerformed
        editarPrecio();
    }//GEN-LAST:event_btnEditarPrecioActionPerformed

    private void btnEditSctockEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditSctockEstadoActionPerformed
        editarStockYEstado();
    }//GEN-LAST:event_btnEditSctockEstadoActionPerformed

    private void configurarTabla() {
        tblAnimales.setModel(modelo);
        tblAnimales.setRowHeight(28);
        tblAnimales.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 13));
        jScrollPane1.setBorder(BorderFactory.createLineBorder(new Color(225, 231, 229)));
    }

    public final void cargarDatos() {
        modelo.setRowCount(0);

        try {
            List<Animal> animales = animalService.findAll();
            for (Animal animal : animales) {
                String nombreRaza = String.valueOf(animal.getIdRaza());
                Raza raza = razaService.findById(animal.getIdRaza()).orElse(null);
                if (raza != null) {
                    nombreRaza = raza.getNombre();
                }

                modelo.addRow(new Object[]{
                        animal.getIdAnimal(),
                        nombreRaza,
                        animal.getNombre(),
                        animal.getSexo(),
                        animal.getEdad(),
                        String.format(Locale.US, "S/ %.2f", animal.getPrecio()),
                        animal.getStock(),
                        animal.getEstado()
                });
            }
        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(this, "No se pudieron cargar los animales.");
        }
    }

    private void editarPrecio() {
        int fila = tblAnimales.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un animal de la tabla.");
            return;
        }

        int modelRow = tblAnimales.convertRowIndexToModel(fila);
        int idAnimal = (int) modelo.getValueAt(modelRow, 0);
        String nombre = String.valueOf(modelo.getValueAt(modelRow, 2));
        double precioActual;
        try {
            precioActual = Double.parseDouble(modelo.getValueAt(modelRow, 5).toString().replace("S/", "").trim());
        } catch (Exception ex) {
            precioActual = animalService.findById(idAnimal).map(Animal::getPrecio).orElse(0.0);
        }

        String input = JOptionPane.showInputDialog(this, "Nuevo precio para \"" + nombre + "\":", String.valueOf(precioActual));
        if (input == null) {
            return;
        }

        try {
            double nuevoPrecio = Double.parseDouble(input.trim());
            if (nuevoPrecio <= 0) {
                JOptionPane.showMessageDialog(this, "El precio debe ser mayor a 0.");
                return;
            }

            Animal animal = animalService.findById(idAnimal).orElse(null);
            if (animal == null) {
                JOptionPane.showMessageDialog(this, "Animal no encontrado.");
                return;
            }

            animal.setPrecio(nuevoPrecio);
            int result = animalService.update(animal);
            if (result > 0) {
                JOptionPane.showMessageDialog(this, "Precio actualizado.");
                cargarDatos();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo actualizar el precio.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un precio válido.");
        }
    }

    private void editarStockYEstado() {
        int fila = tblAnimales.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un animal de la tabla.");
            return;
        }

        int modelRow = tblAnimales.convertRowIndexToModel(fila);
        int idAnimal = (int) modelo.getValueAt(modelRow, 0);
        String nombre = String.valueOf(modelo.getValueAt(modelRow, 2));

        Animal animal = animalService.findById(idAnimal).orElse(null);
        if (animal == null) {
            JOptionPane.showMessageDialog(this, "Animal no encontrado.");
            return;
        }

        JTextField txtStock = new JTextField(String.valueOf(animal.getStock()));
        JComboBox<String> cmbEstado = new JComboBox<>(new String[]{"Disponible", "Vendido"});
        cmbEstado.setSelectedItem(animal.getEstado());

        JPanel panel = new JPanel(new java.awt.GridLayout(0, 1, 0, 8));
        panel.setBorder(new javax.swing.border.EmptyBorder(8, 8, 8, 8));
        panel.add(new JLabel("Stock:"));
        panel.add(txtStock);
        panel.add(new JLabel("Estado:"));
        panel.add(cmbEstado);

        int result = JOptionPane.showConfirmDialog(this, panel, "Editar stock y estado de \"" + nombre + "\"",
                JOptionPane.OK_CANCEL_OPTION);
        if (result != JOptionPane.OK_OPTION) {
            return;
        }

        try {
            int nuevoStock = Integer.parseInt(txtStock.getText().trim());
            if (nuevoStock < 0) {
                JOptionPane.showMessageDialog(this, "El stock no puede ser negativo.");
                return;
            }

            animal.setStock(nuevoStock);
            animal.setEstado(String.valueOf(cmbEstado.getSelectedItem()));

            int res = animalService.update(animal);
            if (res > 0) {
                JOptionPane.showMessageDialog(this, "Stock y estado actualizados.");
                cargarDatos();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo actualizar.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un stock válido.");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditSctockEstado;
    private javax.swing.JButton btnEditarPrecio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAnimales;
    // End of variables declaration//GEN-END:variables
}
