/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion.GuiAdmin;

import Aplicacion.Service.ClienteService;
import Aplicacion.Service.UsuarioService;
import Aplicacion.Service.VentaService;
import Dominio.Modelo.Cliente;
import Dominio.Modelo.Usuario;
import Dominio.Modelo.Venta;

import java.awt.Color;
import java.awt.Desktop;
import java.awt.Font;
import java.io.File;
import java.io.FileOutputStream;
import java.util.List;
import java.util.Locale;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import com.itextpdf.text.Document;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;

/**
 *
 * @author neker
 */
public class PanelClientes extends javax.swing.JPanel {

    private final ClienteService clienteService = new ClienteService();
    private final UsuarioService usuarioService = new UsuarioService();
    private final VentaService ventaService = new VentaService();
    private final DefaultTableModel modelo = new DefaultTableModel(
            new Object[]{"ID Cliente", "Nombre Cliente", "DNI", "Telefono", "Direccion", "Nro de Compras"}, 0
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    /**
     * Creates new form PanelAnimales
     */
    public PanelClientes() {
        initComponents();
        setBackground(new Color(244, 247, 246));
        configurarTabla();
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        btnExportarPDF = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(920, 630));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(25, 40, 37));
        jLabel1.setText("Clientes registrados");

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Cliente", "Nombre Cliente", "DNI", "Telefono", "Direccion", "Nro de Compras"
            }
        ));
        jScrollPane1.setViewportView(tblClientes);

        btnExportarPDF.setText("Exportar PDF");
        btnExportarPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarPDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(508, 508, 508)
                        .addComponent(btnExportarPDF)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExportarPDF)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnExportarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarPDFActionPerformed
        // TODO add your handling code here:
        exportarPDF();
    }//GEN-LAST:event_btnExportarPDFActionPerformed

    private void configurarTabla() {
        tblClientes.setModel(modelo);
        tblClientes.setRowHeight(28);
        tblClientes.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 13));
        jScrollPane1.setBorder(BorderFactory.createLineBorder(new Color(225, 231, 229)));
    }

    public final void cargarDatos() {
        modelo.setRowCount(0);
        try {
            List<Venta> todasLasVentas = ventaService.findAll();
            List<Cliente> clientes = clienteService.findAll();
            for (Cliente cliente : clientes) {
                String nombre = "Desconocido";
                Usuario usuario = usuarioService.findById(cliente.getIdUsuario()).orElse(null);
                if (usuario != null) {
                    nombre = usuario.getNombre();
                }

                int nroCompras = (int) todasLasVentas.stream()
                        .filter(v -> v.getIdCliente() == cliente.getIdCliente())
                        .count();

                modelo.addRow(new Object[]{
                        cliente.getIdCliente(),
                        nombre,
                        cliente.getDni(),
                        cliente.getTelefono(),
                        cliente.getDireccion(),
                        nroCompras
                });
            }
        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(this, "No se pudieron cargar los clientes.");
        }
    }

    private void exportarPDF() {
        if (modelo.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "No hay datos para exportar.");
            return;
        }
        try {
            File archivo = new File("Reporte_Clientes_" + System.currentTimeMillis() + ".pdf");
            Document documento = new Document();
            PdfWriter.getInstance(documento, new FileOutputStream(archivo));
            documento.open();

            com.itextpdf.text.Font titulo = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18);
            com.itextpdf.text.Font subtitulo = FontFactory.getFont(FontFactory.HELVETICA, 12);

            Paragraph p1 = new Paragraph("REPORTE DE CLIENTES", titulo);
            p1.setAlignment(Paragraph.ALIGN_CENTER);
            documento.add(p1);
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph("Fecha de generacion: " + java.time.LocalDateTime.now(), subtitulo));
            documento.add(new Paragraph(" "));

            PdfPTable pdfTable = new PdfPTable(6);
            pdfTable.setWidthPercentage(100);

            com.itextpdf.text.Font fuenteCabecera = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 11);
            String[] headers = {"ID", "Nombre", "DNI", "Telefono", "Direccion", "Nro Compras"};
            for (String h : headers) {
                PdfPCell c = new PdfPCell(new Phrase(h, fuenteCabecera));
                c.setBackgroundColor(new com.itextpdf.text.BaseColor(34, 139, 34));
                c.setHorizontalAlignment(PdfPCell.ALIGN_CENTER);
                pdfTable.addCell(c);
            }

            for (int fila = 0; fila < modelo.getRowCount(); fila++) {
                for (int col = 0; col < modelo.getColumnCount(); col++) {
                    pdfTable.addCell(String.valueOf(modelo.getValueAt(fila, col)));
                }
            }

            documento.add(pdfTable);
            documento.close();

            JOptionPane.showMessageDialog(this, "PDF generado correctamente.");
            Desktop.getDesktop().open(archivo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al generar PDF\n" + e.getMessage());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportarPDF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblClientes;
    // End of variables declaration//GEN-END:variables
}
