/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion.GuiAdmin;

import Aplicacion.Service.ClienteService;
import Aplicacion.Service.UsuarioService;
import Aplicacion.Service.VentaService;
import Dominio.Modelo.Cliente;
import Dominio.Modelo.Usuario;
import Dominio.Modelo.Venta;

import java.awt.Color;
import java.awt.Font;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.util.Locale;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import com.itextpdf.text.Document;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;

/**
 *
 * @author neker
 */
public class PanelVentas extends javax.swing.JPanel {

    private final ClienteService clienteService = new ClienteService();
    private final UsuarioService usuarioService = new UsuarioService();
    private final VentaService ventaService = new VentaService();
    private final DefaultTableModel modelo = new DefaultTableModel(
            new Object[]{"ID Venta", "Cliente", "Fecha", "Total"}, 0
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    /**
     * Creates new form PanelAnimales
     */
    public PanelVentas() {
        initComponents();
        setBackground(new Color(244, 247, 246));
        configurarTabla();
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVentas = new javax.swing.JTable();
        btnExportarPDF = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(920, 630));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(25, 40, 37));
        jLabel1.setText("Ventas registradas");

        tblVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Venta", "Cliente", "Fecha", "Total"
            }
        ));
        jScrollPane1.setViewportView(tblVentas);

        btnExportarPDF.setText("Exportar PDF");
        btnExportarPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarPDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 413, Short.MAX_VALUE)
                        .addComponent(btnExportarPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExportarPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnExportarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarPDFActionPerformed
            // TODO add your handling code here:
            exportarPDF();
    }//GEN-LAST:event_btnExportarPDFActionPerformed

    private void configurarTabla() {
        tblVentas.setModel(modelo);
        tblVentas.setRowHeight(28);
        tblVentas.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 13));
        jScrollPane1.setBorder(BorderFactory.createLineBorder(new Color(225, 231, 229)));
    }

    public final void cargarDatos() {
        modelo.setRowCount(0);
        try {
            for (Venta venta : ventaService.findAll()) {
                String nombreCliente = "Desconocido";
                Cliente cliente = clienteService.findById(venta.getIdCliente()).orElse(null);
                if (cliente != null) {
                    Usuario usuario = usuarioService.findById(cliente.getIdUsuario()).orElse(null);
                    if (usuario != null) {
                        nombreCliente = usuario.getNombre();
                    }
                }

                modelo.addRow(new Object[]{
                        venta.getIdVenta(),
                        nombreCliente,
                        venta.getFecha(),
                        String.format(Locale.US, "S/ %.2f", venta.getTotal())
                });
            }
        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(this, "No se pudieron cargar las ventas.");
        }
    }

    private void exportarPDF() {
        try {
            File archivo = new File("Reporte_Ventas_" + System.currentTimeMillis() + ".pdf");
            Document documento = new Document();
            PdfWriter.getInstance(documento, new FileOutputStream(archivo));
            documento.open();

            com.itextpdf.text.Font titulo = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18);
            com.itextpdf.text.Font subtitulo = FontFactory.getFont(FontFactory.HELVETICA, 12);

            Paragraph p1 = new Paragraph("REPORTE ADMINISTRATIVO DE VENTAS", titulo);
            p1.setAlignment(Paragraph.ALIGN_CENTER);
            documento.add(p1);
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph("Fecha de generación: " + java.time.LocalDateTime.now(), subtitulo));
            documento.add(new Paragraph(" "));

            PdfPTable pdfTable = new PdfPTable(4);
            pdfTable.setWidthPercentage(100);

            com.itextpdf.text.Font fuenteCabecera = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12);
            PdfPCell c1 = new PdfPCell(new Phrase("ID Venta", fuenteCabecera));
            PdfPCell c2 = new PdfPCell(new Phrase("Cliente", fuenteCabecera));
            PdfPCell c3 = new PdfPCell(new Phrase("Fecha", fuenteCabecera));
            PdfPCell c4 = new PdfPCell(new Phrase("Total", fuenteCabecera));

            c1.setBackgroundColor(new com.itextpdf.text.BaseColor(34, 139, 34));
            c2.setBackgroundColor(new com.itextpdf.text.BaseColor(34, 139, 34));
            c3.setBackgroundColor(new com.itextpdf.text.BaseColor(34, 139, 34));
            c4.setBackgroundColor(new com.itextpdf.text.BaseColor(34, 139, 34));
            c1.setHorizontalAlignment(PdfPCell.ALIGN_CENTER);
            c2.setHorizontalAlignment(PdfPCell.ALIGN_CENTER);
            c3.setHorizontalAlignment(PdfPCell.ALIGN_CENTER);
            c4.setHorizontalAlignment(PdfPCell.ALIGN_CENTER);

            pdfTable.addCell(c1);
            pdfTable.addCell(c2);
            pdfTable.addCell(c3);
            pdfTable.addCell(c4);

            double totalVentas = 0;
            for (int fila = 0; fila < tblVentas.getRowCount(); fila++) {
                pdfTable.addCell(String.valueOf(tblVentas.getValueAt(fila, 0)));
                pdfTable.addCell(String.valueOf(tblVentas.getValueAt(fila, 1)));
                pdfTable.addCell(String.valueOf(tblVentas.getValueAt(fila, 2)));
                pdfTable.addCell(String.valueOf(tblVentas.getValueAt(fila, 3)));

                String total = String.valueOf(tblVentas.getValueAt(fila, 3)).replace("S/", "").trim();
                totalVentas += Double.parseDouble(total);
            }

            documento.add(pdfTable);
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph("TOTAL VENDIDO: S/ " + String.format("%.2f", totalVentas),
                    FontFactory.getFont(FontFactory.HELVETICA_BOLD, 13)));
            documento.close();

            JOptionPane.showMessageDialog(this, "PDF generado correctamente.");
            Desktop.getDesktop().open(archivo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al generar PDF\n" + e.getMessage());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportarPDF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVentas;
    // End of variables declaration//GEN-END:variables
}
