/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion.GuiAdmin;

import Aplicacion.Service.AnimalService;
import Aplicacion.Service.ClienteService;
import Aplicacion.Service.VentaService;
import Dominio.Modelo.Animal;
import Dominio.Modelo.Venta;

import java.util.Locale;
import java.util.List;

/**
 *
 * @author neker
 */
public class PanelDashboard extends javax.swing.JPanel {

    private final AnimalService animalService = new AnimalService();
    private final VentaService ventaService = new VentaService();
    private final ClienteService clienteService = new ClienteService();

    /**
     * Creates new form PanelDashboard
     */
    public PanelDashboard() {
        initComponents();
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAnimales = new javax.swing.JPanel();
        txtAnimales = new javax.swing.JLabel();
        NumAnimales = new javax.swing.JLabel();
        txtDescriptionAnimales = new javax.swing.JLabel();
        jPanelStock = new javax.swing.JPanel();
        txtStockTotal = new javax.swing.JLabel();
        NumStockTotal = new javax.swing.JLabel();
        txtDescriptionStockTotal = new javax.swing.JLabel();
        jPanelStockBajo = new javax.swing.JPanel();
        txtStockBajo = new javax.swing.JLabel();
        NumStockBajo = new javax.swing.JLabel();
        txtDescriptionStockBajo = new javax.swing.JLabel();
        jPanelMontoVendido = new javax.swing.JPanel();
        txtMontoVendido = new javax.swing.JLabel();
        NumMontoVendido = new javax.swing.JLabel();
        txtDescriptionMontoVendido = new javax.swing.JLabel();
        jPanelVentas = new javax.swing.JPanel();
        txtVentas = new javax.swing.JLabel();
        NumVentas = new javax.swing.JLabel();
        txtDescriptionVentas = new javax.swing.JLabel();
        jPanelClientes = new javax.swing.JPanel();
        TxtClientes = new javax.swing.JLabel();
        NumClientes = new javax.swing.JLabel();
        txtDescriptionClientes = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(920, 630));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelAnimales.setBackground(new java.awt.Color(255, 255, 255));
        jPanelAnimales.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelAnimales.setPreferredSize(new java.awt.Dimension(286, 285));

        txtAnimales.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtAnimales.setForeground(new java.awt.Color(25, 40, 37));
        txtAnimales.setText("Animales");

        NumAnimales.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        NumAnimales.setForeground(new java.awt.Color(35, 132, 110));
        NumAnimales.setText("15");

        txtDescriptionAnimales.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtDescriptionAnimales.setForeground(new java.awt.Color(150, 160, 156));
        txtDescriptionAnimales.setText("Cantidad total de animales registrados");

        javax.swing.GroupLayout jPanelAnimalesLayout = new javax.swing.GroupLayout(jPanelAnimales);
        jPanelAnimales.setLayout(jPanelAnimalesLayout);
        jPanelAnimalesLayout.setHorizontalGroup(
            jPanelAnimalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAnimalesLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanelAnimalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescriptionAnimales)
                    .addComponent(NumAnimales)
                    .addComponent(txtAnimales))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanelAnimalesLayout.setVerticalGroup(
            jPanelAnimalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAnimalesLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(txtAnimales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NumAnimales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(txtDescriptionAnimales)
                .addGap(25, 25, 25))
        );

        add(jPanelAnimales, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, -1, -1));

        jPanelStock.setBackground(new java.awt.Color(255, 255, 255));
        jPanelStock.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelStock.setPreferredSize(new java.awt.Dimension(286, 285));

        txtStockTotal.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtStockTotal.setForeground(new java.awt.Color(25, 40, 37));
        txtStockTotal.setText("Stock Total");

        NumStockTotal.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        NumStockTotal.setForeground(new java.awt.Color(35, 132, 110));
        NumStockTotal.setText("15");

        txtDescriptionStockTotal.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtDescriptionStockTotal.setForeground(new java.awt.Color(150, 160, 156));
        txtDescriptionStockTotal.setText("Suma de todas las unidades disponibles");

        javax.swing.GroupLayout jPanelStockLayout = new javax.swing.GroupLayout(jPanelStock);
        jPanelStock.setLayout(jPanelStockLayout);
        jPanelStockLayout.setHorizontalGroup(
            jPanelStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStockLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NumStockTotal)
                    .addComponent(txtDescriptionStockTotal)
                    .addComponent(txtStockTotal))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanelStockLayout.setVerticalGroup(
            jPanelStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStockLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(txtStockTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NumStockTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(txtDescriptionStockTotal)
                .addGap(23, 23, 23))
        );

        add(jPanelStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 15, -1, -1));

        jPanelStockBajo.setBackground(new java.awt.Color(255, 255, 255));
        jPanelStockBajo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelStockBajo.setPreferredSize(new java.awt.Dimension(286, 285));

        txtStockBajo.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtStockBajo.setForeground(new java.awt.Color(25, 40, 37));
        txtStockBajo.setText("Stock bajo");

        NumStockBajo.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        NumStockBajo.setForeground(new java.awt.Color(35, 132, 110));
        NumStockBajo.setText("15");

        txtDescriptionStockBajo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtDescriptionStockBajo.setForeground(new java.awt.Color(150, 160, 156));
        txtDescriptionStockBajo.setText("Animales con 5 o menos unidades");

        javax.swing.GroupLayout jPanelStockBajoLayout = new javax.swing.GroupLayout(jPanelStockBajo);
        jPanelStockBajo.setLayout(jPanelStockBajoLayout);
        jPanelStockBajoLayout.setHorizontalGroup(
            jPanelStockBajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStockBajoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelStockBajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NumStockBajo)
                    .addComponent(txtStockBajo)
                    .addComponent(txtDescriptionStockBajo, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanelStockBajoLayout.setVerticalGroup(
            jPanelStockBajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStockBajoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(txtStockBajo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NumStockBajo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addComponent(txtDescriptionStockBajo)
                .addGap(26, 26, 26))
        );

        add(jPanelStockBajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(625, 15, -1, -1));

        jPanelMontoVendido.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMontoVendido.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelMontoVendido.setPreferredSize(new java.awt.Dimension(286, 285));

        txtMontoVendido.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtMontoVendido.setForeground(new java.awt.Color(25, 40, 37));
        txtMontoVendido.setText("Moto vendido");

        NumMontoVendido.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        NumMontoVendido.setForeground(new java.awt.Color(35, 132, 110));
        NumMontoVendido.setText("15");

        txtDescriptionMontoVendido.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtDescriptionMontoVendido.setForeground(new java.awt.Color(150, 160, 156));
        txtDescriptionMontoVendido.setText("Total acumulado de todas las ventas");

        javax.swing.GroupLayout jPanelMontoVendidoLayout = new javax.swing.GroupLayout(jPanelMontoVendido);
        jPanelMontoVendido.setLayout(jPanelMontoVendidoLayout);
        jPanelMontoVendidoLayout.setHorizontalGroup(
            jPanelMontoVendidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMontoVendidoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelMontoVendidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NumMontoVendido)
                    .addComponent(txtDescriptionMontoVendido, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMontoVendido))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanelMontoVendidoLayout.setVerticalGroup(
            jPanelMontoVendidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMontoVendidoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(txtMontoVendido)
                .addGap(18, 18, 18)
                .addComponent(NumMontoVendido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(txtDescriptionMontoVendido)
                .addGap(31, 31, 31))
        );

        add(jPanelMontoVendido, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, -1, -1));

        jPanelVentas.setBackground(new java.awt.Color(255, 255, 255));
        jPanelVentas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelVentas.setPreferredSize(new java.awt.Dimension(286, 285));

        txtVentas.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtVentas.setForeground(new java.awt.Color(25, 40, 37));
        txtVentas.setText("Ventas");

        NumVentas.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        NumVentas.setForeground(new java.awt.Color(35, 132, 110));
        NumVentas.setText("15");

        txtDescriptionVentas.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtDescriptionVentas.setForeground(new java.awt.Color(150, 160, 156));
        txtDescriptionVentas.setText("Número total de ventas realizadas");

        javax.swing.GroupLayout jPanelVentasLayout = new javax.swing.GroupLayout(jPanelVentas);
        jPanelVentas.setLayout(jPanelVentasLayout);
        jPanelVentasLayout.setHorizontalGroup(
            jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVentasLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NumVentas)
                    .addComponent(txtVentas)
                    .addComponent(txtDescriptionVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanelVentasLayout.setVerticalGroup(
            jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVentasLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(txtVentas)
                .addGap(18, 18, 18)
                .addComponent(NumVentas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(txtDescriptionVentas)
                .addGap(31, 31, 31))
        );

        add(jPanelVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jPanelClientes.setBackground(new java.awt.Color(255, 255, 255));
        jPanelClientes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelClientes.setPreferredSize(new java.awt.Dimension(286, 285));

        TxtClientes.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        TxtClientes.setForeground(new java.awt.Color(25, 40, 37));
        TxtClientes.setText("Clientes");

        NumClientes.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        NumClientes.setForeground(new java.awt.Color(35, 132, 110));
        NumClientes.setText("15");

        txtDescriptionClientes.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtDescriptionClientes.setForeground(new java.awt.Color(150, 160, 156));
        txtDescriptionClientes.setText("Total de clientes registrados");
        txtDescriptionClientes.setToolTipText("");

        javax.swing.GroupLayout jPanelClientesLayout = new javax.swing.GroupLayout(jPanelClientes);
        jPanelClientes.setLayout(jPanelClientesLayout);
        jPanelClientesLayout.setHorizontalGroup(
            jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClientesLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescriptionClientes)
                    .addComponent(NumClientes)
                    .addComponent(TxtClientes))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanelClientesLayout.setVerticalGroup(
            jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClientesLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(TxtClientes)
                .addGap(26, 26, 26)
                .addComponent(NumClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(txtDescriptionClientes)
                .addGap(30, 30, 30))
        );

        add(jPanelClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    public final void cargarDatos() {
        int totalAnimales = 0;
        int stockTotal = 0;
        int stockBajo = 0;
        int totalVentas = 0;
        double montoVentas = 0;
        int totalClientes = 0;

        try {
            List<Animal> animales = animalService.findAll();
            totalAnimales = animales.size();
            stockTotal = animales.stream().mapToInt(Animal::getStock).sum();
            stockBajo = (int) animales.stream().filter(a -> a.getStock() <= 5).count();
        } catch (RuntimeException ignored) {
        }

        try {
            List<Venta> ventas = ventaService.findAll();
            totalVentas = ventas.size();
            montoVentas = ventas.stream().mapToDouble(Venta::getTotal).sum();
        } catch (RuntimeException ignored) {
        }

        try {
            totalClientes = clienteService.findAll().size();
        } catch (RuntimeException ignored) {
        }

        NumAnimales.setText(String.valueOf(totalAnimales));
        NumStockTotal.setText(String.valueOf(stockTotal));
        NumStockBajo.setText(String.valueOf(stockBajo));
        NumVentas.setText(String.valueOf(totalVentas));
        NumMontoVendido.setText(String.format(Locale.US, "S/ %.2f", montoVentas));
        NumClientes.setText(String.valueOf(totalClientes));
    }

   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NumAnimales;
    private javax.swing.JLabel NumClientes;
    private javax.swing.JLabel NumMontoVendido;
    private javax.swing.JLabel NumStockBajo;
    private javax.swing.JLabel NumStockTotal;
    private javax.swing.JLabel NumVentas;
    private javax.swing.JLabel TxtClientes;
    private javax.swing.JPanel jPanelAnimales;
    private javax.swing.JPanel jPanelClientes;
    private javax.swing.JPanel jPanelMontoVendido;
    private javax.swing.JPanel jPanelStock;
    private javax.swing.JPanel jPanelStockBajo;
    private javax.swing.JPanel jPanelVentas;
    private javax.swing.JLabel txtAnimales;
    private javax.swing.JLabel txtDescriptionAnimales;
    private javax.swing.JLabel txtDescriptionClientes;
    private javax.swing.JLabel txtDescriptionMontoVendido;
    private javax.swing.JLabel txtDescriptionStockBajo;
    private javax.swing.JLabel txtDescriptionStockTotal;
    private javax.swing.JLabel txtDescriptionVentas;
    private javax.swing.JLabel txtMontoVendido;
    private javax.swing.JLabel txtStockBajo;
    private javax.swing.JLabel txtStockTotal;
    private javax.swing.JLabel txtVentas;
    // End of variables declaration//GEN-END:variables
}
